apiVersion: v2
name: n8n-scalable
description: A scalable n8n deployment with queue mode and Redis Streams support
type: application
version: 1.0.0
appVersion: "1.19.4"

keywords:
  - n8n
  - workflow
  - automation
  - queue
  - redis
  - streams

home: https://n8n.io
sources:
  - https://github.com/n8n-io/n8n

maintainers:
  - name: DevOps Team
    email: devops@company.com

dependencies:
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "12.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled 