apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n-scalable.fullname" . }}-config
  labels:
    {{- include "n8n-scalable.labels" . | nindent 4 }}
data:
  # Basic configuration
  N8N_HOST: {{ .Values.n8n.env.N8N_HOST | default "localhost" | quote }}
  N8N_PORT: "5678"
  N8N_PROTOCOL: {{ .Values.n8n.env.N8N_PROTOCOL | default "http" | quote }}
  
  # Database configuration
  DB_TYPE: {{ .Values.n8n.env.DB_TYPE | default "postgresdb" | quote }}
  DB_POSTGRESDB_HOST: {{ include "n8n-scalable.databaseHost" . | quote }}
  DB_POSTGRESDB_PORT: {{ include "n8n-scalable.databasePort" . | quote }}
  DB_POSTGRESDB_DATABASE: {{ include "n8n-scalable.databaseName" . | quote }}
  DB_POSTGRESDB_USER: {{ include "n8n-scalable.databaseUsername" . | quote }}
  
  # Queue configuration
  EXECUTIONS_PROCESS: {{ .Values.n8n.env.EXECUTIONS_PROCESS | default "queue" | quote }}
  QUEUE_BULL_REDIS_HOST: {{ include "n8n-scalable.redisHost" . | quote }}
  QUEUE_BULL_REDIS_PORT: {{ include "n8n-scalable.redisPort" . | quote }}
  QUEUE_BULL_REDIS_DB: {{ .Values.n8n.env.QUEUE_BULL_REDIS_DB | default "0" | quote }}
  QUEUE_BULL_REDIS_PASSWORD: {{ .Values.n8n.env.QUEUE_BULL_REDIS_PASSWORD | default "" | quote }}
  QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD: {{ .Values.n8n.env.QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD | default "5000" | quote }}
  QUEUE_BULL_MAX_STALLED_COUNT: {{ .Values.n8n.env.QUEUE_BULL_MAX_STALLED_COUNT | default "1" | quote }}
  
  # Redis Streams configuration
  REDIS_STREAMS_ENABLED: {{ .Values.n8n.env.REDIS_STREAMS_ENABLED | default "true" | quote }}
  REDIS_STREAMS_CONSUMER_GROUP: {{ .Values.n8n.env.REDIS_STREAMS_CONSUMER_GROUP | default "n8n-consumers" | quote }}
  REDIS_STREAMS_BLOCK_TIME: {{ .Values.n8n.env.REDIS_STREAMS_BLOCK_TIME | default "5000" | quote }}
  REDIS_STREAMS_MAX_LEN: {{ .Values.n8n.env.REDIS_STREAMS_MAX_LEN | default "1000" | quote }}
  
  # Queue health check
  {{- if .Values.n8n.queue.health.enabled }}
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  QUEUE_HEALTH_CHECK_PORT: {{ .Values.n8n.queue.health.port | quote }}
  {{- end }}
  
  # General n8n configuration
  WEBHOOK_URL: {{ .Values.n8n.env.WEBHOOK_URL | default "http://localhost:30678/" | quote }}
  GENERIC_TIMEZONE: {{ .Values.n8n.env.GENERIC_TIMEZONE | default "UTC" | quote }}
  TZ: {{ .Values.n8n.env.GENERIC_TIMEZONE | default "UTC" | quote }}
  
  # Security
  N8N_BASIC_AUTH_ACTIVE: {{ .Values.n8n.env.N8N_BASIC_AUTH_ACTIVE | default "true" | quote }}
  N8N_BASIC_AUTH_USER: {{ .Values.n8n.env.N8N_BASIC_AUTH_USER | default "admin" | quote }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.env.N8N_BASIC_AUTH_PASSWORD | required "N8N_BASIC_AUTH_PASSWORD is required in values" | quote }}
  
  # Metrics and monitoring
  N8N_METRICS: {{ .Values.n8n.env.N8N_METRICS | default "true" | quote }}
  N8N_DIAGNOSTICS_ENABLED: {{ .Values.n8n.env.N8N_DIAGNOSTICS_ENABLED | default "false" | quote }}
  
  # Additional environment variables from the env section
  {{- range $key, $value := .Values.n8n.env }}
  {{- if not (has $key (list "N8N_HOST" "N8N_PROTOCOL" "DB_TYPE" "EXECUTIONS_PROCESS" "QUEUE_BULL_REDIS_HOST" "QUEUE_BULL_REDIS_PORT" "WEBHOOK_URL" "GENERIC_TIMEZONE" "N8N_BASIC_AUTH_ACTIVE" "N8N_BASIC_AUTH_USER" "N8N_BASIC_AUTH_PASSWORD" "N8N_METRICS" "N8N_DIAGNOSTICS_ENABLED")) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }} 