{{- if .Values.n8n.main.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-scalable.fullname" . }}-main
  labels:
    {{- include "n8n-scalable.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
  {{- with .Values.n8n.main.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.n8n.main.service.type }}
  ports:
    - port: {{ .Values.n8n.main.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.n8n.main.service.type "NodePort") .Values.n8n.main.service.nodePort }}
      nodePort: {{ .Values.n8n.main.service.nodePort }}
      {{- end }}
    {{- if .Values.n8n.queue.health.enabled }}
    - port: {{ .Values.n8n.queue.health.port }}
      targetPort: health
      protocol: TCP
      name: health
    {{- end }}
  selector:
    {{- include "n8n-scalable.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main
{{- end }} 